version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: DockerFile.web
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=myapp.local
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GerenciadorDeProdutos
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
