version: '3.8'

services:
  web:
    image: wyveo/nginx-php-fpm:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/src
    environment:
      - VIRTUAL_HOST=myapp.local
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GerenciadorDeProdutos
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
